name: C/C++ CI

on:
  watch:
    types: started

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        brew install xmake
        brew info xmake
    - name: build
      run: |
        xmake build
        xmake show
